Repository canonical/operator, pull requests merged in 2023-10, with the labels that each got.

#1025 test: add type hints to test_framework
  CHANGES.md
  ops/framework.py
  pyproject.toml
  test/test_framework.py
Labels: type hints

#1028 test: add type hints to test_main
  ops/framework.py
  pyproject.toml
  test/charms/test_main/src/charm.py
  test/charms/test_smoke/src/charm.py
  test/test_main.py
Labels: type hints

#1024 fix: push_path and pull_path include empty directories
  ops/model.py
  test/test_model.py
  test/test_testing.py
Labels: bug

#1030 test: add type hints to pebble-related tests
  ops/charm.py
  ops/model.py
  ops/pebble.py
  ops/testing.py
  pyproject.toml
  test/fake_pebble.py
  test/pebble_cli.py
  test/test_pebble.py
  test/test_real_pebble.py
  test/test_testing.py
Labels: type hints

#1034 chore: remove as much 'if typing.TYPE_CHECKING:' as possible
  docs/conf.py
  ops/charm.py
  ops/framework.py
  ops/log.py
  ops/main.py
  ops/model.py
  ops/pebble.py
  ops/storage.py
  ops/testing.py
Labels: type hints

#1031 docs: make pebble.Client.remove_path and Container.remove_path docs consistent
  ops/model.py
  ops/pebble.py
Labels: docs

#1036 ci: Pass LIBJUJU_VERSION_SPECIFIER to the mysql-k8s-operator unit tests
  .github/workflows/db-charm-tests.yaml
Labels: bug

#1032 feat: narrow the type for 'app' and 'unit' in relation events
  ops/charm.py
  test/test_charm.py
Labels: feature

#1049 feat: provide a clearer exception when the Pebble socket is missing
  ops/pebble.py
  test/test_pebble.py
Labels: feature

#1044 docs: document more of the exceptions that may be raised
  HACKING.md
  ops/charm.py
  ops/framework.py
  ops/model.py
  ops/pebble.py
  ops/storage.py
  ops/testing.py
Labels: docs

#1041 feat: add Unit.reboot for machine charms
  CHANGES.md
  ops/model.py
  ops/testing.py
  test/test_model.py
  test/test_testing.py
Labels: feature

#1052 [JUJU-4553] Update README.md to simplify and better align with docs
  README.md
  ops/__init__.py
Labels: docs
