Repository canonical/operator, pull requests merged in 2023-11, with the labels that each got.

#1059 chore: remove the executable bit from all the .py files
  ops/charm.py
  ops/framework.py
  ops/jujuversion.py
  ops/main.py
  ops/storage.py
  ops/testing.py
  test/test_charm.py
  test/test_framework.py
  test/test_helpers.py
  test/test_jujuversion.py
  test/test_log.py
  test/test_main.py
  test/test_model.py
  test/test_pebble.py
  test/test_real_pebble.py
  test/test_storage.py
Labels: feature, small item

#1057 fix: reduce mode of SQLite storage file to 0o600
  ops/storage.py
  test/test_storage.py
Labels: bug

#1067 feat: secret owners do not auto-peek, and can use refresh
  ops/model.py
  ops/testing.py
  test/test_testing.py
Labels: harness

#1082 fix: handle users/groups with no names in push_path
  ops/model.py
  test/test_model.py
  test/test_testing.py
Labels: bug
